// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llmcoc/server/internal/handlers (interfaces: CharacterLLMFactory)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/mocks/mock_char_llm.go -package=mocks github.com/llmcoc/server/internal/handlers CharacterLLMFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/llmcoc/server/internal/models"
	llm "github.com/llmcoc/server/internal/services/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterLLMFactory is a mock of CharacterLLMFactory interface.
type MockCharacterLLMFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterLLMFactoryMockRecorder
	isgomock struct{}
}

// MockCharacterLLMFactoryMockRecorder is the mock recorder for MockCharacterLLMFactory.
type MockCharacterLLMFactoryMockRecorder struct {
	mock *MockCharacterLLMFactory
}

// NewMockCharacterLLMFactory creates a new mock instance.
func NewMockCharacterLLMFactory(ctrl *gomock.Controller) *MockCharacterLLMFactory {
	mock := &MockCharacterLLMFactory{ctrl: ctrl}
	mock.recorder = &MockCharacterLLMFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterLLMFactory) EXPECT() *MockCharacterLLMFactoryMockRecorder {
	return m.recorder
}

// LoadProvider mocks base method.
func (m *MockCharacterLLMFactory) LoadProvider(role models.AgentRole) (llm.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProvider", role)
	ret0, _ := ret[0].(llm.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProvider indicates an expected call of LoadProvider.
func (mr *MockCharacterLLMFactoryMockRecorder) LoadProvider(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProvider", reflect.TypeOf((*MockCharacterLLMFactory)(nil).LoadProvider), role)
}
