// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llmcoc/server/internal/services/llm (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/mocks/mock_llm.go -package=mocks github.com/llmcoc/server/internal/services/llm Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	llm "github.com/llmcoc/server/internal/services/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockProvider) Chat(ctx context.Context, messages []llm.ChatMessage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, messages)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockProviderMockRecorder) Chat(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockProvider)(nil).Chat), ctx, messages)
}

// ChatStream mocks base method.
func (m *MockProvider) ChatStream(ctx context.Context, messages []llm.ChatMessage) (<-chan string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, messages)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockProviderMockRecorder) ChatStream(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockProvider)(nil).ChatStream), ctx, messages)
}
