// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llmcoc/server/internal/services/agent (interfaces: AgentRunner)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/mocks/mock_agent.go -package=mocks github.com/llmcoc/server/internal/services/agent AgentRunner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/llmcoc/server/internal/services/agent"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRunner is a mock of AgentRunner interface.
type MockAgentRunner struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRunnerMockRecorder
	isgomock struct{}
}

// MockAgentRunnerMockRecorder is the mock recorder for MockAgentRunner.
type MockAgentRunnerMockRecorder struct {
	mock *MockAgentRunner
}

// NewMockAgentRunner creates a new mock instance.
func NewMockAgentRunner(ctrl *gomock.Controller) *MockAgentRunner {
	mock := &MockAgentRunner{ctrl: ctrl}
	mock.recorder = &MockAgentRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRunner) EXPECT() *MockAgentRunnerMockRecorder {
	return m.recorder
}

// RunAsync mocks base method.
func (m *MockAgentRunner) RunAsync(ctx context.Context, gctx agent.GameContext) <-chan agent.RunResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAsync", ctx, gctx)
	ret0, _ := ret[0].(<-chan agent.RunResult)
	return ret0
}

// RunAsync indicates an expected call of RunAsync.
func (mr *MockAgentRunnerMockRecorder) RunAsync(ctx, gctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAsync", reflect.TypeOf((*MockAgentRunner)(nil).RunAsync), ctx, gctx)
}
