// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llmcoc/server/internal/handlers (interfaces: ProviderFactory)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/mocks/mock_factory.go -package=mocks github.com/llmcoc/server/internal/handlers ProviderFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/llmcoc/server/internal/models"
	llm "github.com/llmcoc/server/internal/services/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockProviderFactory is a mock of ProviderFactory interface.
type MockProviderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockProviderFactoryMockRecorder
	isgomock struct{}
}

// MockProviderFactoryMockRecorder is the mock recorder for MockProviderFactory.
type MockProviderFactoryMockRecorder struct {
	mock *MockProviderFactory
}

// NewMockProviderFactory creates a new mock instance.
func NewMockProviderFactory(ctrl *gomock.Controller) *MockProviderFactory {
	mock := &MockProviderFactory{ctrl: ctrl}
	mock.recorder = &MockProviderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderFactory) EXPECT() *MockProviderFactoryMockRecorder {
	return m.recorder
}

// NewProvider mocks base method.
func (m *MockProviderFactory) NewProvider(cfg *models.LLMProviderConfig, modelName string, maxTokens int, temperature float32) llm.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewProvider", cfg, modelName, maxTokens, temperature)
	ret0, _ := ret[0].(llm.Provider)
	return ret0
}

// NewProvider indicates an expected call of NewProvider.
func (mr *MockProviderFactoryMockRecorder) NewProvider(cfg, modelName, maxTokens, temperature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewProvider", reflect.TypeOf((*MockProviderFactory)(nil).NewProvider), cfg, modelName, maxTokens, temperature)
}
