// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llmcoc/server/internal/services/agent (interfaces: AgentRunner)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/mocks/mock_agent.go -package=mocks github.com/llmcoc/server/internal/services/agent AgentRunner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/llmcoc/server/internal/services/agent"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRunner is a mock of AgentRunner interface.
type MockAgentRunner struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRunnerMockRecorder
	isgomock struct{}
}

// MockAgentRunnerMockRecorder is the mock recorder for MockAgentRunner.
type MockAgentRunnerMockRecorder struct {
	mock *MockAgentRunner
}

// NewMockAgentRunner creates a new mock instance.
func NewMockAgentRunner(ctrl *gomock.Controller) *MockAgentRunner {
	mock := &MockAgentRunner{ctrl: ctrl}
	mock.recorder = &MockAgentRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRunner) EXPECT() *MockAgentRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockAgentRunner) Run(ctx context.Context, gctx agent.GameContext) (agent.RunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, gctx)
	ret0, _ := ret[0].(agent.RunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockAgentRunnerMockRecorder) Run(ctx, gctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAgentRunner)(nil).Run), ctx, gctx)
}

// RunWriter 模拟基础方法。
func (m *MockAgentRunner) RunWriter(ctx context.Context, gctx agent.GameContext, direction string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWriter", ctx, gctx, direction)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWriter 声明期望调用。
func (mr *MockAgentRunnerMockRecorder) RunWriter(ctx, gctx, direction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWriter", reflect.TypeOf((*MockAgentRunner)(nil).RunWriter), ctx, gctx, direction)
}

// RunWriterStream 模拟基础方法。
func (m *MockAgentRunner) RunWriterStream(ctx context.Context, gctx agent.GameContext, direction string, onToken func(string)) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWriterStream", ctx, gctx, direction, onToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWriterStream 声明期望调用。
func (mr *MockAgentRunnerMockRecorder) RunWriterStream(ctx, gctx, direction, onToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWriterStream", reflect.TypeOf((*MockAgentRunner)(nil).RunWriterStream), ctx, gctx, direction, onToken)
}

// NOTE: RunPainter 模拟基础方法。
func (m *MockAgentRunner) RunPainter(ctx context.Context, gctx agent.GameContext, prompt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPainter", ctx, gctx, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NOTE: RunPainter 声明期望调用。
func (mr *MockAgentRunnerMockRecorder) RunPainter(ctx, gctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPainter", reflect.TypeOf((*MockAgentRunner)(nil).RunPainter), ctx, gctx, prompt)
}
