// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/llmcoc/server/internal/services/agent (interfaces: AgentRunner)
//
// Generated by this command:
//
//	mockgen -destination=internal/handlers/mocks/mock_agent.go -package=mocks github.com/llmcoc/server/internal/services/agent AgentRunner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/llmcoc/server/internal/services/agent"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRunner is a mock of AgentRunner interface.
type MockAgentRunner struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRunnerMockRecorder
	isgomock struct{}
}

// MockAgentRunnerMockRecorder is the mock recorder for MockAgentRunner.
type MockAgentRunnerMockRecorder struct {
	mock *MockAgentRunner
}

// NewMockAgentRunner creates a new mock instance.
func NewMockAgentRunner(ctrl *gomock.Controller) *MockAgentRunner {
	mock := &MockAgentRunner{ctrl: ctrl}
	mock.recorder = &MockAgentRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRunner) EXPECT() *MockAgentRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockAgentRunner) Run(ctx context.Context, gctx agent.GameContext) (agent.RunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, gctx)
	ret0, _ := ret[0].(agent.RunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockAgentRunnerMockRecorder) Run(ctx, gctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAgentRunner)(nil).Run), ctx, gctx)
}
